version: "3.8"

services:
  mssql:
    image: mcr.microsoft.com/mssql/server
    container_name: mssql
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Strong(!)Password"
